import json

notebook = {
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Video_Translator_Colab.ipynb",
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "intro"
      },
      "source": [
        "# 🚀 NullOfflineVideoTranslator (Google Colab Edition)\n",
        "Убедитесь, что вы включили видеокарту: `Среда выполнения` -> `Сменить среду выполнения` -> `T4 GPU`."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "main_cell"
      },
      "outputs": [],
      "source": [
        "# @title ⚙️ Интерактивная настройка и запуск\n",
        "# @markdown Заполните поля ниже и нажмите кнопку Play слева (▶️).\n",
        "\n",
        "# @markdown --- \n",
        "# @markdown **Настройки GitHub (обязательно)**\n",
        "GITHUB_REPO = \"NullCoreDeveloper/NullOfflineVideoTranslator\" # @param {type:\"string\"}\n",
        "GITHUB_TOKEN = \"\" # @param {type:\"string\"}\n",
        "# @markdown *Если репозиторий публичный, оставьте GITHUB_TOKEN пустым. Если приватный — вставьте Personal Access Token (Classic).* \n",
        "\n",
        "# @markdown --- \n",
        "# @markdown **Настройки нейросетей (обязательно)**\n",
        "HF_TOKEN = \"\" # @param {type:\"string\"}\n",
        "GEMINI_KEYS = \"\" # @param {type:\"string\"}\n",
        "\n",
        "# @markdown --- \n",
        "# @markdown **Что переводим?**\n",
        "INPUT_MODE = \"YouTube Link\" # @param [\"YouTube Link\", \"Local File\"]\n",
        "VIDEO_URL = \"https://youtu.be/XQcf7NVxcVA?si=g37mQ_vUWvIF59X8\" # @param {type:\"string\"}\n",
        "# @markdown *Если выбрали Local File, при запуске ячейки появится кнопка для загрузки файла с ПК.*\n",
        "# @markdown \n",
        "# @markdown **На какой язык перевести?**\n",
        "TARGET_LANGUAGE = \"ru\" # @param [\"ru\", \"en\", \"es\", \"fr\", \"de\", \"it\", \"pt\", \"pl\", \"tr\", \"nl\", \"cs\", \"ar\", \"zh-cn\", \"ja\", \"hu\", \"ko\", \"hi\"]\n",
        "\n",
        "import os\n",
        "import subprocess\n",
        "\n",
        "print(\"⏳ Подготовка окружения...\")\n",
        "\n",
        "# 0. Сброс директории (защита от матрешки при перезапуске)\n",
        "os.chdir('/content')\n",
        "\n",
        "# 1. Клонирование репозитория\n",
        "if not os.path.exists(\"video-translator\"):\n",
        "    if GITHUB_TOKEN:\n",
        "        repo_url = f\"https://{GITHUB_TOKEN}@github.com/{GITHUB_REPO}.git\"\n",
        "    else:\n",
        "        repo_url = f\"https://github.com/{GITHUB_REPO}.git\"\n",
        "    \n",
        "    !git clone {repo_url} video-translator\n",
        "\n",
        "os.chdir(\"video-translator\")\n",
        "\n",
        "# 1.5 Подготовка видео (ранняя загрузка, чтобы не ждать установок)\n",
        "LOCAL_FILE = None\n",
        "if INPUT_MODE == 'Local File':\n",
        "    from google.colab import files\n",
        "    print(\"\\n👇 Пожалуйста, выберите видеофайл на вашем компьютере для загрузки:\")\n",
        "    uploaded = files.upload()\n",
        "    if not uploaded:\n",
        "        print(\"❌ Ошибка: Файл не был загружен! Остановка.\")\n",
        "        import sys; sys.exit(1)\n",
        "    LOCAL_FILE = list(uploaded.keys())[0]\n",
        "    print(f\"✅ Файл {LOCAL_FILE} успешно загружен! Начинаю установку нейросетей...\\n\")\n",
        "elif INPUT_MODE == 'YouTube Link':\n",
        "    print(f\"\\n🎥 Пробуем скачать видео с YouTube: {VIDEO_URL}\")\n",
        "    !pip install -q yt-dlp\n",
        "    import subprocess, re\n",
        "    try:\n",
        "        raw_title = subprocess.check_output(['yt-dlp', '--print', '%(title)s', VIDEO_URL]).decode('utf-8').strip()\n",
        "        clean_title = re.sub(r'[^\\w\\s-]', '', raw_title).strip().replace(' ', '_')[:12]\n",
        "        if not clean_title: clean_title = 'video'\n",
        "        LOCAL_FILE = f'{clean_title}.mp4'\n",
        "        subprocess.run(['yt-dlp', '-f', 'bestvideo[height<=1080]+bestaudio/best', '--merge-output-format', 'mp4', '-o', LOCAL_FILE, VIDEO_URL], check=True)\n",
        "        if not os.path.exists(LOCAL_FILE): raise Exception('Файл не создался')\n",
        "        print(f\"✅ Видео успешно скачано: {LOCAL_FILE}. Начинаю установку нейросетей...\\n\")\n",
        "    except Exception as e:\n",
        "        print(\"\\n====================================================================\")\n",
        "        print(\"❌ КРИТИЧЕСКАЯ ОШИБКА: yt-dlp не смог скачать видео с YouTube!\")\n",
        "        print(\"Скорее всего, сработала защита от ботов на IP-адресах Google Colab.\")\n",
        "        print(\"💡 РЕШЕНИЕ 1: В меню Colab нажмите 'Среда выполнения' -> 'Отключиться и удалить среду', затем запустите ячейку заново.\")\n",
        "        print(\"💡 РЕШЕНИЕ 2: Скачайте видео на ПК, выберите выше 'INPUT_MODE = Local File' и загрузите его вручную.\")\n",
        "        print(\"====================================================================\\n\")\n",
        "        import sys; sys.exit(1)\n",
        "\n",
        "# 2. Создание .env файла\n",
        "with open('.env', 'w') as f:\n",
        "    f.write(f\"HF_TOKEN={HF_TOKEN}\\n\")\n",
        "    f.write(f\"GEMINI_API_KEYS={GEMINI_KEYS}\\n\")\n",
        "    f.write(\"PROXY_URL=\\n\")\n",
        "print(\"✅ Ключи загружены!\")\n",
        "\n",
        "# 3. Установка зависимостей (тихая установка)\n",
        "print(\"📦 Установка нейросетей (это займет 2-3 минуты)...\")\n",
        "!apt-get install -yq rubberband-cli\n",
        "!pip install -q yt-dlp pydub ffmpeg-python demucs librosa python-dotenv google-generativeai onnxruntime-gpu onnx huggingface_hub pyrubberband \"numpy<2.0\" \"pandas<2.2.2\"\n",
        "!pip install -q git+https://github.com/m-bain/whisperx.git\n",
        "print(\"✅ Зависимости установлены!\")\n",
        "\n",
        "# 3.5 Скачивание моделей XTTS\n",
        "print(\"📥 Скачивание и подготовка моделей XTTS...\")\n",
        "import sys\n",
        "sys.path.append('.')\n",
        "import install\n",
        "install.download_and_quantize_xtts(HF_TOKEN)\n",
        "\n",
        "# 4. Запуск перевода\n",
        "print(f\"🎥 Обработка файла: {LOCAL_FILE} -> {TARGET_LANGUAGE}\")\n",
        "!python3 main.py \"{LOCAL_FILE}\" --target_lang \"{TARGET_LANGUAGE}\"\n",
        "\n",
        "import glob\n",
        "result_files = glob.glob(\"*_translated_*/*.mp4\")\n",
        "if result_files:\n",
        "    latest_file = max(result_files, key=os.path.getctime)\n",
        "    print(f\"\\n🎉 Готово! Видео переведено и сохранено.\")\n",
        "    from google.colab import output, files\n",
        "    from IPython.display import HTML, display\n",
        "    import base64\n",
        "    \n",
        "    def download_video():\n",
        "        files.download(latest_file)\n",
        "    \n",
        "    output.register_callback('notebook.download_video', download_video)\n",
        "    \n",
        "    html = '''\n",
        "    <br><br>\n",
        "    <button id=\"download_btn\" style=\"\n",
        "        background-color: #4CAF50; border: none; color: white;\n",
        "        padding: 15px 32px; text-align: center; text-decoration: none;\n",
        "        display: inline-block; font-size: 16px; margin: 4px 2px;\n",
        "        cursor: pointer; border-radius: 12px; font-weight: bold;\n",
        "        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);\">\n",
        "        📥 СКАЧАТЬ ВИДЕО\n",
        "    </button>\n",
        "    <script>\n",
        "    document.querySelector(\"#download_btn\").onclick = function() {\n",
        "        google.colab.kernel.invokeFunction('notebook.download_video', [], {});\n",
        "    };\n",
        "    </script>\n",
        "    '''\n",
        "    display(HTML(html))\n",
        "else:\n",
        "    print(\"\\n⚠️ Итоговое видео не найдено. Возможно, произошла ошибка.\")"
      ]
    }
  ]
}

with open("NullOfflineVideoTranslator.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)
    
print("Playbook generated successfully: NullOfflineVideoTranslator.ipynb")
